name: NoLongNames
main: net.daboross.bukkitdev.nolongnames.NoLongNames
version: 1.2
author: Dabo Ross
description: Stops long names
commands:
  reloadnln:
    description: Reloads NoLongName's config
    usage: /<command>
    permission: nolongnames.reload